apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
        - image: jasonblanchard/node-hello:2272101f27130304cb8fdbab4220b3e859163411
          name: hello
          ports:
            - containerPort: 8080
